/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.ProductoData;
import Entidades.Mesero;
import Entidades.Producto;
import LoginMozo.InternalLoginMozo;
import LoginMozo.LoginMozo;
import VistasInternas.InternalAdminMozos;
import VistasInternas.InternalDetallePedido;
import VistasInternas.InternalFactura;
import VistasInternas.InternalMesas;
import VistasInternas.InternalPedidos2;
import VistasInternas.InternalProductos;
import VistasInternas.InternalReservas;
import VistasInternas.ListadoInternalMesas;
import VistasInternas.ListadoInternalMozos;
import VistasInternas.ListadoInternalProductos;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matiSqui
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    ProductoData proData = new ProductoData();

    

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setHoraActual();
        armarCabecera();
        mostrarProductos();
        mensajePrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dateC = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        btActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuMozos = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenuItem();
        MenuDetalles = new javax.swing.JMenuItem();
        MenuFactura = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuReservas = new javax.swing.JMenuItem();
        MenuMesas = new javax.swing.JMenuItem();
        MenuPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuListMozos = new javax.swing.JMenuItem();
        MenuListMesas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back2.PNG"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Productos");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Productos que tienen poca cantidad.");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("HOY ES:");

        btIniciar.setText("Abrir");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Manejo de la sesion.");

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(dateC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btIniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4))
                    .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5)
                                .addGap(43, 43, 43)
                                .addComponent(dateC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(escritorioLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btIniciar)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(btActualizar)))))
                .addContainerGap(396, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addGap(131, 131, 131))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dateC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btIniciar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalir)
                        .addGap(35, 35, 35))))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 119, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(91, 40, 70));
        jMenuBar1.setForeground(new java.awt.Color(91, 40, 70));

        jMenu1.setText("Administrar");

        MenuMozos.setText("Manejo Mozos");
        MenuMozos.setActionCommand("");
        MenuMozos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMozosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuMozos);

        MenuProductos.setText("Productos");
        MenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProductos);

        MenuDetalles.setText("Detalle Pedidos");
        MenuDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDetallesActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDetalles);

        MenuFactura.setText("Factura");
        MenuFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFacturaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFactura);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salon");

        MenuReservas.setText("Reservas");
        MenuReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReservasActionPerformed(evt);
            }
        });
        jMenu2.add(MenuReservas);

        MenuMesas.setText("Mesas");
        MenuMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMesasActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMesas);

        MenuPedidos.setText("Pedidos");
        MenuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPedidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Listados");

        MenuListMozos.setText("Listado Mozos");
        MenuListMozos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListMozosActionPerformed(evt);
            }
        });
        jMenu3.add(MenuListMozos);

        MenuListMesas.setText("Listado Mesas");
        MenuListMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListMesasActionPerformed(evt);
            }
        });
        jMenu3.add(MenuListMesas);

        jMenuItem1.setText("Listado Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMozosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMozosActionPerformed

        InternalAdminMozos internalMozos = new InternalAdminMozos();
        escritorio.add(internalMozos);
        internalMozos.setVisible(true);
        
    }//GEN-LAST:event_MenuMozosActionPerformed

    private void MenuListMozosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListMozosActionPerformed

        ListadoInternalMozos listadoMozos = new ListadoInternalMozos();
        escritorio.add(listadoMozos);
        listadoMozos.setVisible(true);


    }//GEN-LAST:event_MenuListMozosActionPerformed

    private void MenuMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMesasActionPerformed

        InternalMesas internalMesas = new InternalMesas();
        escritorio.add(internalMesas);
        internalMesas.setVisible(true);

    }//GEN-LAST:event_MenuMesasActionPerformed

    private void MenuListMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListMesasActionPerformed

        ListadoInternalMesas listadoMesas = new ListadoInternalMesas();
        escritorio.add(listadoMesas);
        listadoMesas.setVisible(true);
        
        
    }//GEN-LAST:event_MenuListMesasActionPerformed

    private void MenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductosActionPerformed

        InternalProductos internalProductos = new InternalProductos();
        escritorio.add(internalProductos);
        internalProductos.setVisible(true);

    }//GEN-LAST:event_MenuProductosActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        
        mostrarProductos();


    }//GEN-LAST:event_btActualizarActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed

        InternalLoginMozo internalLogin = new InternalLoginMozo();
        escritorio.add(internalLogin);
        internalLogin.setVisible(true);

    }//GEN-LAST:event_btIniciarActionPerformed

    private void MenuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPedidosActionPerformed

         Mesero mozo = LoginMozo.getMeseroActual();

         if (mozo == null) {
            
             JOptionPane.showMessageDialog(this,"Debe iniciar sesion primero!");
             return;
        }
         
        InternalPedidos2 internalPedidos2 = new InternalPedidos2();
        escritorio.add(internalPedidos2);
        internalPedidos2.setVisible(true);
        
       
     
        JOptionPane.showMessageDialog(this, "Ingresando como: " + mozo.toString());
        

        
    }//GEN-LAST:event_MenuPedidosActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    private void MenuReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReservasActionPerformed

        InternalReservas internalReservas = new InternalReservas();
        escritorio.add(internalReservas);
        internalReservas.setVisible(true);

    }//GEN-LAST:event_MenuReservasActionPerformed

    private void MenuDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDetallesActionPerformed
      
       InternalDetallePedido internalDetalle = new InternalDetallePedido();
       escritorio.add(internalDetalle);
       internalDetalle.setVisible(true);
        
    }//GEN-LAST:event_MenuDetallesActionPerformed

    private void MenuFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFacturaActionPerformed

        InternalFactura internalFactura = new InternalFactura();
        escritorio.add(internalFactura);
        internalFactura.setVisible(true);


    }//GEN-LAST:event_MenuFacturaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        ListadoInternalProductos listadoProdu = new ListadoInternalProductos();
        escritorio.add(listadoProdu);
        listadoProdu.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuDetalles;
    private javax.swing.JMenuItem MenuFactura;
    private javax.swing.JMenuItem MenuListMesas;
    private javax.swing.JMenuItem MenuListMozos;
    private javax.swing.JMenuItem MenuMesas;
    private javax.swing.JMenuItem MenuMozos;
    private javax.swing.JMenuItem MenuPedidos;
    private javax.swing.JMenuItem MenuProductos;
    private javax.swing.JMenuItem MenuReservas;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btSalir;
    private com.toedter.calendar.JDateChooser dateC;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

public void setHoraActual(){
        
    LocalDate fechaActual = LocalDate.now();
    Date date = Date.from(fechaActual.atStartOfDay(ZoneId.systemDefault()).toInstant());
    
    dateC.setDate(date);
    
}

public void armarCabecera(){
    
    modelo.addColumn("codigo");
    modelo.addColumn("nombre");
    modelo.addColumn("stock");
    
    jTable1.setModel(modelo);
    
}

public void mostrarProductos(){
    
    
    modelo.setRowCount(0);
    
    for (Producto producto : proData.listarProductosMenores()) {
        
        Object [] fila = new Object[3];
        
        fila[0] = producto.getCodigo();
        fila[1] = producto.getNombre();
        fila[2] = producto.getCantidad();
        
        modelo.addRow(fila);
        
    }
    
}

public void mensajePrincipal(){
    
    JOptionPane.showMessageDialog(this,"DEBE INICIAR SESION PARA PODER SEGUIR (manejo de sesion)");
    
    
}

}
