/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasInternas;

import Entidades.Mesa;
import Entidades.Mesero;

/**
 *
 * @author matiSqui
 */
public class InternalPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalPedidos
     */
    public InternalPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMesa = new javax.swing.JComboBox<>();
        cbMesero = new javax.swing.JComboBox<>();
        cbxEstado = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btBuscar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manejoPedidos.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 546, 126);

        jLabel2.setText("Mesa:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(73, 184, 31, 16);

        jLabel3.setText("Mozo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(73, 237, 33, 16);

        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(73, 293, 38, 16);

        jLabel5.setText("FechaPedido");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(73, 350, 68, 16);

        getContentPane().add(cbMesa);
        cbMesa.setBounds(184, 181, 194, 22);

        getContentPane().add(cbMesero);
        cbMesero.setBounds(184, 234, 194, 22);

        cbxEstado.setText("Activo/Inactivo");
        getContentPane().add(cbxEstado);
        cbxEstado.setBounds(184, 291, 104, 20);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(184, 350, 194, 22);

        btBuscar.setText("Buscar");
        btBuscar.setToolTipText("");
        getContentPane().add(btBuscar);
        btBuscar.setBounds(410, 180, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JComboBox<Mesa> cbMesa;
    private javax.swing.JComboBox<Mesero> cbMesero;
    private javax.swing.JCheckBox cbxEstado;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
