/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasInternas;

import AccesoADatos.MesaData;
import AccesoADatos.MozoData;
import AccesoADatos.PedidoData;
import Entidades.Mesa;
import Entidades.Mesero;
import Entidades.Pedido;
import LoginMozo.LoginMozo;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matiSqui
 */
public class InternalPedidos2 extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    
    private MesaData meData = new MesaData();
    private PedidoData pedidoData = new PedidoData();
    private MozoData mozoData = new MozoData();
    private Mesero mozoSel = null;
    Pedido pedidoActual = null;

    
    
    /**
     * Creates new form InternalPedidos2
     */
    public InternalPedidos2() {
        initComponents();
        cargarJcbMesa();
        usuarioLog();
        setFecha();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMesa = new javax.swing.JComboBox<>();
        labelMozo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txIdMozo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JCheckBox();
        labelEstado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateC = new com.toedter.calendar.JDateChooser();
        btPedido = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btModificar = new javax.swing.JButton();
        labelEstado1 = new javax.swing.JLabel();
        btVer = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manejoPedidos.PNG"))); // NOI18N

        jLabel2.setText("Seleccione una mesa:");

        labelMozo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelMozo.setText("Usuario:");

        jLabel3.setText("ID Mozo:");

        txIdMozo.setEnabled(false);

        jLabel4.setText("Estado:");

        cbEstado.setText("Pendiente/Pagado");

        labelEstado.setText("estado actual de la mesa:");

        jLabel5.setText("Fecha:");

        btPedido.setText("Hacer pedido");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btNuevo.setText("Nuevo");

        jLabel6.setText("Pendientes de:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btModificar.setText("Modificar");

        labelEstado1.setText("\"\"");

        btVer.setText("Ver");
        btVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txIdMozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbEstado)
                                        .addComponent(cbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btNuevo)
                                        .addComponent(labelEstado)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateC, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(btPedido))
                                        .addComponent(labelEstado1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(196, 196, 196)))
                        .addGap(156, 156, 156))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelMozo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVer)
                        .addGap(101, 101, 101)
                        .addComponent(btModificar)
                        .addGap(109, 109, 109)
                        .addComponent(btSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txIdMozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEstado))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(labelEstado1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNuevo)
                    .addComponent(btPedido))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelMozo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModificar)
                    .addComponent(btSalir)
                    .addComponent(btVer))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        
        try{
            
        //obtengo la mesa del jcomboBox
        Mesa mesaSel = null;
        mesaSel = (Mesa) cbMesa.getSelectedItem();
        //obtengo el id de la mesa
        int idSelMesa = mesaSel.getIdMesa();
        
      
        Integer idMozoSel = Integer.parseInt(txIdMozo.getText());
        //tengo que buscar el mozo en la db, el metodo devuleve un Mozo
        mozoSel = mozoData.buscarMozoId(idMozoSel);

        boolean estadoSel = cbEstado.isSelected();

        
        Date fechaActual = dateC.getDate();
        //paso de un date a un LocalDate
        LocalDate fechaSel = fechaActual.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        
            if (mesaSel == null) {
                
                JOptionPane.showMessageDialog(this, "Debe seleccionar una mesa");
                return;
            }
        
            if (pedidoActual == null) {
                
                //creo el pedido con sus atributos
                Pedido pedidoActual = new Pedido(mesaSel, mozoSel, estadoSel, fechaSel);
                //lo cargo en la base de datos
                pedidoData.cargarPedido(pedidoActual, mesaSel, mozoSel);
            }
            
           
            
    } catch (NumberFormatException ex){
        
        JOptionPane.showMessageDialog(this, "ingrse un elemento valido");
        
    }
        

    }//GEN-LAST:event_btPedidoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    private void btVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerActionPerformed
  cargarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_btVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVer;
    private javax.swing.JCheckBox cbEstado;
    private javax.swing.JComboBox<Mesa> cbMesa;
    private com.toedter.calendar.JDateChooser dateC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelEstado1;
    private javax.swing.JLabel labelMozo;
    private javax.swing.JTextField txIdMozo;
    // End of variables declaration//GEN-END:variables

//cargo el jcomboBox
    public void cargarJcbMesa(){
    
    for (Mesa mesa : meData.listadoMesasaAll() ) {
        
        cbMesa.addItem(mesa);
        
    }
}

//cargo el id del mozo iniciado
    public void usuarioLog(){
    
    Mesero mozo = LoginMozo.getMeseroActual();
     
   txIdMozo.setText(String.valueOf(mozo.getIdMesero()));
   labelMozo.setText(mozo.toString());

}
    
    //set fechaActual
    public void setFecha(){
           LocalDate fechaActual = LocalDate.now();
    Date date = Date.from(fechaActual.atStartOfDay(ZoneId.systemDefault()).toInstant());
    
    dateC.setDate(date);
        
    }
 
    //armar cabecera
    public void armarCabecera(){
        
        modelo.addColumn("id Pedido");
        modelo.addColumn("Mesa");
        modelo.addColumn("Estado");
        modelo.addColumn("Fecha");
        
    }
    
    //cargar la tabla
    public void cargarTabla(){
        Mesero mozo = LoginMozo.getMeseroActual();
        
        
        
        modelo.setRowCount(0);
        
        for (Pedido pedido : pedidoData.listarPedidoId(mozo.getIdMesero())) {
            
            Object [] fila = new Object[0];
            fila [0] = pedido.getIdPedido();
            fila [1] = pedido.getMesa();
            fila [2] = pedido.getMesero();
            fila[3] = pedido.isEstado();
            fila[4] = pedido.getFechaPedido();
           
            modelo.addRow(fila);
            
        }
        
    }
    
}
