/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasInternas;

import AccesoADatos.DetallePedidoData;
import AccesoADatos.MesaData;
import AccesoADatos.PedidoData;
import AccesoADatos.ProductoData;
import Entidades.DetallePedido;
import Entidades.Pedido;
import Entidades.Producto;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matiSqui
 */
public class InternalDetallePedido extends javax.swing.JInternalFrame {

     private DefaultTableModel modelo = new DefaultTableModel();
    
    DetallePedidoData detalleData = new DetallePedidoData();
    DetallePedido detalleActual = null;
    

   
    ProductoData proData = new ProductoData();
    
    PedidoData pedidoData = new PedidoData();
    
    
    /**
     * Creates new form InternalDetallePedido
     */
    public InternalDetallePedido() {
        initComponents();
//        limpiarDetalles();
        cargarJcbPedidos();
        cargarJcbProductos();
//        cargarJcbDetalles();
        armarCabecera();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbPedido = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbProductos = new javax.swing.JComboBox<>();
        txCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        txImporte = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JCheckBox();
        brVerImporte = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btNuevo = new javax.swing.JButton();
        btVer = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txIdMod = new javax.swing.JTextField();
        btBuscarID = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        labelMensaje = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detallesPedidos.PNG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Acá podras gestionar el detalle de los pedidos por medio de su id.");

        jLabel3.setText("Id Pedido:");

        jLabel4.setText("Detalles: ");

        jLabel6.setText("Producto:");

        jLabel7.setText("Cantidad:");

        jLabel8.setText("Importe:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        txImporte.setEnabled(false);

        Guardar.setText("Guardar");
        Guardar.setToolTipText("");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel9.setText("Cancelar detalle:");

        brVerImporte.setText("Ver importe");
        brVerImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brVerImporteActionPerformed(evt);
            }
        });

        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btVer.setText("ver");
        btVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerActionPerformed(evt);
            }
        });

        jLabel14.setText("Modificar un detalle por id");

        btBuscarID.setText("Buscar");
        btBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarIDActionPerformed(evt);
            }
        });

        labelMensaje.setText("\"\"");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Importante!! debe seleccionar el producto antes de cancelar y guardar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(cbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVer))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(34, 34, 34)
                                .addComponent(txIdMod, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btBuscarID))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(1, 1, 1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(brVerImporte))))
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelMensaje)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btNuevo)
                        .addGap(74, 74, 74)
                        .addComponent(Guardar)
                        .addGap(84, 84, 84)
                        .addComponent(btSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btVer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txIdMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarID))
                .addGap(18, 18, 18)
                .addComponent(labelMensaje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brVerImporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(btSalir)
                    .addComponent(btNuevo))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
   
        try{
            restColorComboBox(cbPedido);
            restColorText(txCantidad);
            
            
            Pedido pedido = (Pedido) cbPedido.getSelectedItem();
            
            int idPedido = pedido.getIdPedido();
            pedidoData.buscarPedidoId(idPedido);
            
            
            Producto productoAct = (Producto) cbProductos.getSelectedItem();
            int  idProducto = productoAct.getIdProducto();
            
        
            Integer cantSel = Integer.parseInt(txCantidad.getText());
            
            if (cbPedido == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un pedido");
                setColorComboBox(cbPedido);
                return;
                
            } if (cantSel == 0) {
                
                JOptionPane.showMessageDialog(this, "No puede dejar la cantidad en 0");
                setColorText(txCantidad);
                return;
            }

            //saco el importe del detalle 
            Double precio =  productoAct.getPrecio();
            
            Double precioFinal = cantSel * precio ;
            
           String precioStr = String.valueOf(precioFinal);
            txImporte.setText(precioStr);
  
            
            boolean estadoSel = true;
            
         
            if (detalleActual == null) {
                
                if (cantSel > productoAct.getCantidad()) {
                        
                        JOptionPane.showMessageDialog(this, "No cuenta con esa cantidad de stock: " + cantSel + "de: " + productoAct.getNombre());
                        setColorText(txCantidad);
                        return;
                    }
                
                 //calculo el stock actual
                int cantFinal = productoAct.getCantidad() - cantSel;
                    
                //lo actualizo en la db
                proData.modificarProductoStock(productoAct,cantFinal);
          
                
                detalleActual = new DetallePedido(pedido,productoAct,cantSel,precioFinal,estadoSel);
                detalleData.cargarDetalle(detalleActual, pedido, productoAct);
                
            } else {
                
                System.out.println(detalleActual.getIdDetalle());
                
               
                detalleActual.setProducto(productoAct);
                detalleActual.setCantidadProducto(cantSel);
                if (cbEstado.isSelected()) {
                    
                int cantFinal = productoAct.getCantidad() + cantSel;
                    
                //lo actualizo en la db
                proData.modificarProductoStock(productoAct,cantFinal);
                
                detalleActual.setEstado(false);
                
                detalleData.modificarDetalle(detalleActual);
                    
                }
               
                
            } 
            
            detalleActual = null;
            
            
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error" + ex.getMessage());
            
            
        }

      

    }//GEN-LAST:event_GuardarActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

        
        

    }//GEN-LAST:event_formMouseEntered

    private void brVerImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brVerImporteActionPerformed

        try{
            
            restColorText(txCantidad);
            Integer cantSel = Integer.parseInt(txCantidad.getText());

            if (cantSel != null) {
           
           Producto productoAct = (Producto) cbProductos.getSelectedItem();
           Double precio =  productoAct.getPrecio();

           Double precioFinal = cantSel * precio ;
            
           String precioStr = String.valueOf(precioFinal);
           txImporte.setText(precioStr);
            
            
        } else {
            
            JOptionPane.showMessageDialog(this, "debe seleccionar una cantidad para ver el importe");
            setColorText(txCantidad);
            return;
        } 
        
            
            
        } catch(NumberFormatException ex){
            
            JOptionPane.showMessageDialog(this, "Debe ingresar una elemento valido en cantiad");
            setColorText(txCantidad);
            
        }
        
    }//GEN-LAST:event_brVerImporteActionPerformed

    private void btVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerActionPerformed

        modelo.setRowCount(0);
        
        Pedido pedidoActual = (Pedido)(cbPedido.getSelectedItem());
        
        if (pedidoActual != null) {
            cargarTabla(pedidoActual.getIdPedido());
        } else {
            
            JOptionPane.showMessageDialog(null,"Debe tener un pedido para poder ver sus detalles");
            setColorComboBox(cbPedido);
        }
        

    
        
    }//GEN-LAST:event_btVerActionPerformed

    private void btBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarIDActionPerformed

        limpiarJcbProducto();
        
        try {
             
         restColorText(txIdMod);

            
        Integer idDetalle = Integer.parseInt(txIdMod.getText());

        
        detalleActual = detalleData.buscarDetalle(idDetalle);
       

        if (detalleActual != null) {
        setColorText2(txCantidad);
        txCantidad.setText(String.valueOf(detalleActual.getCantidadProducto()));
        
        
        labelMensaje.setText(detalleActual.toString());
            
         } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún detalle con el ID ingresado.");
            setColorText(txIdMod); 
         }

            }   catch (NumberFormatException ex) {
         
         
        JOptionPane.showMessageDialog(null, "Debe ingresar un número válido en el campo de ID.");
        setColorText(txIdMod);
        
      }


    }//GEN-LAST:event_btBuscarIDActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed

        cbProductos.removeAllItems();
        cargarJcbProductos();

        txCantidad.setText("");
        txImporte.setText("");
        
    }//GEN-LAST:event_btNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton brVerImporte;
    private javax.swing.JButton btBuscarID;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btVer;
    private javax.swing.JCheckBox cbEstado;
    private javax.swing.JComboBox<Pedido> cbPedido;
    private javax.swing.JComboBox<Producto> cbProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextField txIdMod;
    private javax.swing.JTextField txImporte;
    // End of variables declaration//GEN-END:variables

    //cargar jcb Idpedidos
    public void cargarJcbPedidos(){
        
        for (Pedido pedido : pedidoData.listarPedidoAct()) {
            
            cbPedido.addItem(pedido);
              
        }     
    }

    //Cargar jcb productos
    public void cargarJcbProductos(){
        
        for (Producto producto : proData.listarProductos()) {
            
           cbProductos.addItem(producto);
            
        }  
    }
    
     //limpiar los jcb de producto
     private void limpiarJcbProducto() {

        cbProductos.addItem(null);

    }
    
    //cargar jcb detalle
//    public void cargarJcbDetalles(){
//        
//        for (DetallePedido dePedido : detalleData.listarDetalles()) {
//            
//            cbDetallePedido.addItem(dePedido);
//            
//            
//        }
//        
//    }
    
    //armar cabecera
    public void armarCabecera(){
   
        modelo.addColumn("idPedido");
        modelo.addColumn("idDetalle");
        modelo.addColumn("Prod");
        modelo.addColumn("cant");
        modelo.addColumn("importe");
        
        jTable1.setModel(modelo);
        
    }
    
    //cargar tabla
    public void cargarTabla(int id){
      
       
              for (DetallePedido listarDetalle : detalleData.buscarDetalleIdTrue(id)) {
            
            Object [] fila = new Object[5];
            
            System.out.println(listarDetalle.getIdDetalle());
            
            fila[0] = listarDetalle.getPedido().getIdPedido();
            fila[1] = listarDetalle.getIdDetalle();
            fila[2] = listarDetalle.getProducto().getNombre();
            fila[3] = listarDetalle.getCantidadProducto();
            fila[4] = listarDetalle.getImporte();
            
            
            modelo.addRow(fila);
            
        
        
      
    }
    }
   
//metodos para cambiar los border
    public void setColorText(JTextField textField){

        textField.setBorder(BorderFactory.createLineBorder(Color.RED,1));

    }

    //metodos para cambiar los border
    public void setColorText2(JTextField textField){

        textField.setBorder(BorderFactory.createLineBorder(Color.GREEN,1));

    }
    
    //volver al originar
    public void  restColorText(JTextField textField) {

        textField.setBorder(UIManager.getBorder("TextField.border"));
    }
  
     // Método para cambiar el borde de un JComboBox a color rojo
    public static void setColorComboBox(JComboBox<?> comboBox) {
        comboBox.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
    }

    // Método para restablecer el borde original de un JComboBox
    public static void restColorComboBox(JComboBox<?> comboBox) {
        comboBox.setBorder(UIManager.getBorder("ComboBox.border"));
    }
    
}
