/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasInternas;

import AccesoADatos.MozoData;
import Entidades.Mesero;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matiSqui
 */
public class ListadoInternalMozos extends javax.swing.JInternalFrame {
    
       private DefaultTableModel modelo = new DefaultTableModel();
        private MozoData mozoData= new MozoData();
        private Mesero mozo = null;
       

    /**
     * Creates new form ListadoInternalMozos
     */
    public ListadoInternalMozos() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btActivos = new javax.swing.JButton();
        btInactivos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMozos = new javax.swing.JTable();
        txMensaje = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listadoMozos.PNG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Seleccione que listado quiere ver");

        btActivos.setText("Mozos activos");
        btActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActivosActionPerformed(evt);
            }
        });

        btInactivos.setText("Mozos inactivos");
        btInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInactivosActionPerformed(evt);
            }
        });

        jLabel3.setText("or");

        jTableMozos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMozos);

        txMensaje.setText("\"\"");

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btActivos)
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(72, 72, 72)
                .addComponent(btInactivos))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txMensaje)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSalir)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btActivos)
                    .addComponent(btInactivos)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txMensaje)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btSalir)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActivosActionPerformed
        
        txMensaje.setText("Resultado de la busqueda de mozos: [Activos]");
        mostrarMozosActivos();
//        modelo.setRowCount(0);
   
    }//GEN-LAST:event_btActivosActionPerformed

    private void btInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInactivosActionPerformed
        txMensaje.setText("Resultado de la busqueda de mozos: [Inactivos]");
        mostrarMozosInactivos();
//        modelo.setRowCount(0);
    }//GEN-LAST:event_btInactivosActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActivos;
    private javax.swing.JButton btInactivos;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableMozos;
    private javax.swing.JLabel txMensaje;
    // End of variables declaration//GEN-END:variables

public void armarCabecera(){
    
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("DNI");
    
    jTableMozos.setModel(modelo);
   
    
}


public void mostrarMozosActivos(){
    
        modelo.setRowCount(0);

        for (Mesero mesero : mozoData.listarMozosActivos()) {
        
            Object[] fila = new Object[4];
            
            fila[0] = mesero.getIdMesero();
            fila[1] = mesero.getNombre();
            fila[2] = mesero.getApellido();
            fila[3] = mesero.getDni();
            
            
            modelo.addRow(fila);
    }
 
}

public void mostrarMozosInactivos(){
    
        modelo.setRowCount(0);

        for (Mesero mesero : mozoData.listarMozosInactivos()) {
        
            Object[] fila = new Object[4];
            
            fila[0] = mesero.getIdMesero();
            fila[1] = mesero.getNombre();
            fila[2] = mesero.getApellido();
            fila[3] = mesero.getDni();
            
            
            modelo.addRow(fila);
    }
 
}



}
